import{a as v,S as q,i}from"./assets/vendor-Do60_h77.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const P="55519599-d6063fdf91732cac9901be169",B="https://pixabay.com/api/",m=async(o,t)=>(await v.get(B,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data,g=document.querySelector(".gallery"),y=document.querySelector(".loader"),f=document.querySelector(".load-more");let $=new q(".gallery a",{captionsData:"alt",captionDelay:250});const h=o=>{const t=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:n,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${r}</p>
          <p class="info-item"><b>Views</b> ${n}</p>
          <p class="info-item"><b>Comments</b> ${w}</p>
          <p class="info-item"><b>Downloads</b> ${S}</p>
        </div>
      </li>
    `).join("");g.insertAdjacentHTML("beforeend",t),$.refresh()},M=()=>{g.innerHTML=""},p=()=>{y.classList.remove("is-hidden")},L=()=>{y.classList.add("is-hidden")},b=()=>{f.classList.remove("is-hidden")},d=()=>{f.classList.add("is-hidden")},I=document.querySelector(".form"),O=document.querySelector(".load-more");let c="",l=1,u=0;I.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements.searchQuery.value.trim(),!c){i.warning({message:"Please enter a search query!"});return}l=1,M(),d(),p();try{const t=await m(c,l);if(u=t.totalHits,t.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(t.hits),u>15&&b()}catch{i.error({message:"Something went wrong! Please try again later."})}finally{L(),o.target.reset()}});O.addEventListener("click",async()=>{l+=1,d(),p();try{const o=await m(c,l);h(o.hits);const t=document.querySelector(".gallery-item");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}l*15>=u?(i.info({message:"We're sorry, but you've reached the end of search results."}),d()):b()}catch{i.error({message:"Something went wrong! Please try again later."})}finally{L()}});
//# sourceMappingURL=index.js.map
